Improve api key creation logic

diff --git a/scripts/code-repo/generate_secrets b/scripts/code-repo/generate_secrets
--- a/scripts/code-repo/generate_secrets
+++ b/scripts/code-repo/generate_secrets
@@ -17,8 +17,16 @@ API_KEY_BODY=$(jq -nc \
 API_KEY_RESPONSE=$(np api-key create --format json --body "$API_KEY_BODY")
 
 API_KEY=$(echo "$API_KEY_RESPONSE" | jq -r .api_key)
+API_KEY_ID=$(echo "$API_KEY_RESPONSE" | jq -r .id)
 
-echo "Created api key for ci"
+if [[ -n "$API_KEY_ID" ]]; then
+  echo "Created ci api key: $API_KEY_ID"
+else
+  echo "Error creating ci api key"
+  echo "$API_API_KEY_RESPONSE" | jq
+
+  exit 1
+fi
 
 CODE_REPOSITORY_SECRETS="{\"NP_API_KEY\": \"$API_KEY\"}"
 
